### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by M4xi1m3** [Omega-Numworks/Omega-Website#2]
Due to copyright issues, the current image can't be used. We need a way to have new ones.
I have two ideas :
- Take new ones, edit them a bit to make them better
- Use numworks' STL files to make 3D renders

I think the second is the best one, since it would lead to high quality pictures at no cost.
The current images should also be removed from the repo and the commit history (rebase, edit, force-push?).

**Comment by quentinguidee** [comment]
All images have been deleted from all commits. I replaced them by screenshots of Omega.
